console.log('hello, world');
var h1Selector = document.querySelector('h1');
console.log(h1Selector);
console.dir(h1Selector);
var explanation = document.querySelector('#explanation');
console.log(explanation);
console.dir(explanation);
var hint = document.querySelector('.hint');
console.log(hint);
console.dir(hint);
var pSelector = document.querySelectorAll('p');
console.log(pSelector);
var exampleLink = document.querySelectorAll('.example-link');
console.log(exampleLink);
