const width = 20;
const height = 10;
const area = height * width;
console.log('What is the value of Area?', area);
console.log('What is the type of area?', typeof area);
const bill = 35;
const payment = 70;
const change = payment - bill;
console.log('What is the change?', change);
console.log('What is the type of Change?', typeof change);
const quizzes = 70;
const midterm = 80;
const final = 90;
const grade = (quizzes + midterm + final) / 3;
console.log('What is the value of grade?', grade);
console.log('What is the type of grade?', typeof grade);
const firstName = 'Frank';
const lastName = 'Bishop';
const fullName = firstName + ' ' + lastName;
console.log('What is my full name?', fullName);
console.log('What is the type of fullName?', typeof fullName);
const pH = 8;
const isAcidic = pH < 7;
console.log('Is ph acidic?', isAcidic);
console.log('What is type of isAcidic', typeof isAcidic);
const headCount = 30;
const isSparta = headCount === 300;
console.log('Is the headcount isSparta?', isSparta);
console.log('What is the type of isSparta?', typeof isSparta);
let motto = fullName;
motto = fullName + ' is the GOAT';
console.log('What is my motto?', motto);
console.log('What is type of motto', typeof motto);
